config/routes.rb
IrrationalMind::Application.routes.draw do
  root to: 'irrationals#new'
  resources :irrationals

end

app/models/e_fraction.rb
# == Schema Information
#
# Table name: e_fractions
#
#  id            :integer          not null, primary key
#  irrational_id :integer
#  numerator     :integer
#  denominator   :integer
#  error         :decimal(, )
#  created_at    :datetime
#  updated_at    :datetime
#  power         :integer
#

class EFraction < ActiveRecord::Base
  belongs_to :irrational

  validates_presence_of :irrational_id, :numerator, :denominator
end

app/models/fraction.rb
# == Schema Information
#
# Table name: fractions
#
#  id            :integer          not null, primary key
#  irrational_id :integer
#  numerator     :integer
#  denominator   :integer
#  error         :decimal(, )
#  created_at    :datetime
#  updated_at    :datetime
#

class Fraction < ActiveRecord::Base
  belongs_to :irrational

  validates_presence_of :irrational_id, :numerator, :denominator
end

app/models/irrational.rb
# == Schema Information
#
# Table name: irrationals
#
#  id                :integer          not null, primary key
#  input             :decimal(, )
#  created_at        :datetime
#  updated_at        :datetime
#  exact_numerator   :decimal(, )
#  exact_denominator :decimal(, )
#

class Irrational < ActiveRecord::Base
  has_many :fractions
  has_many :pi_fractions
  has_many :sqrt_fractions
  has_many :e_fractions
  validates_presence_of :input
end

app/models/pi_fraction.rb
# == Schema Information
#
# Table name: pi_fractions
#
#  id            :integer          not null, primary key
#  numerator     :integer
#  denominator   :integer
#  error         :decimal(, )
#  created_at    :datetime
#  updated_at    :datetime
#  irrational_id :integer
#

class PiFraction < ActiveRecord::Base
  belongs_to :irrational

  validates_presence_of :irrational_id, :numerator, :denominator
end

app/models/sqrt_fraction.rb
# == Schema Information
#
# Table name: sqrt_fractions
#
#  id            :integer          not null, primary key
#  irrational_id :integer
#  numerator     :integer
#  denominator   :integer
#  error         :decimal(, )
#  root          :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class SqrtFraction < ActiveRecord::Base
  belongs_to :irrational

  validates_presence_of :irrational_id, :numerator, :denominator, :root
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/irrationals_controller.rb
class IrrationalsController < ApplicationController
  before_action :set_irrational, only: [:show, :edit, :update, :destroy]

  # GET /irrationals
  # GET /irrationals.json
  def index
    @irrationals = Irrational.all
  end

  # GET /irrationals/1
  # GET /irrationals/1.json
  def show
    @frac_types = [:fractions, :pi_fractions, :sqrt_fractions, :e_fractions]
  end

  # GET /irrationals/new
  def new
    @irrational = Irrational.new
  end

  # GET /irrationals/1/edit
  def edit
  end

  # POST /irrationals
  # POST /irrationals.json
  def create
    @irrational = Irrational.new(irrational_params)

    if @irrational.valid?
      set_exact
      implant_fractions(Fraction, @irrational.input.frac, 10000)
      implant_fractions(PiFraction, @irrational.input/Math::PI, 10000)
      implant_fractions_and_function(SqrtFraction, Proc.new { |x| Math.sqrt(x) }, :root, 2)
      implant_fractions_and_function(EFraction, Proc.new { |x| Math::E ** x }, :power, 1)
    end
    respond_to do |format|
      if @irrational.save
        format.html { redirect_to @irrational, notice: 'Irrational was successfully created.' }
        format.json { render action: 'show', status: :created, location: @irrational }
      else
        format.html { render action: 'new' }
        format.json { render json: @irrational.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /irrationals/1
  # PATCH/PUT /irrationals/1.json
  def update
    respond_to do |format|
      if @irrational.update(irrational_params)
        if @irrational.valid?
          set_exact
          implant_fractions(Fraction, @irrational.input.frac, 10000)
          implant_fractions(PiFraction, @irrational.input/Math::PI, 1000)
          implant_fractions_and_function(SqrtFraction, Proc.new { |x| Math.sqrt(x) }, :root, 2)
          implant_fractions_and_function(EFraction, Proc.new { |x| Math::E ** x }, :power, 1)
        end
        format.html { redirect_to @irrational, notice: 'Irrational was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @irrational.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /irrationals/1
  # DELETE /irrationals/1.json
  def destroy
    @irrational.destroy
    respond_to do |format|
      format.html { redirect_to irrationals_url }
      format.json { head :no_content }
    end
  end

  def set_exact
    a = @irrational.input.frac
    @irrational.exact_numerator = a.numerator + @irrational.input.to_i * a.denominator
    @irrational.exact_denominator = a.denominator
    @irrational.save
  end

  def implant_fractions(model, value, max_iterations)
    model.where(irrational_id: @irrational.id).delete_all # clear out potentially old data
    min_tolerance = 0.1
    current_numerator = 0
    current_denominator = 1
    current_test = current_numerator.to_f/current_denominator
    seen_significance = -1
    (1..max_iterations).each do
      if current_test < value
        current_numerator += 1
      else
        current_denominator += 1
      end
      current_test = current_numerator.to_f/current_denominator
      test_tolerance = (current_test - value).abs.to_d
      if test_tolerance < min_tolerance # found a closer value
        min_tolerance = test_tolerance
        sign, significant_digits, base, exponent = test_tolerance.split
        if significant_digits == "0"  # perfect match
          return model.create(numerator: current_numerator, denominator: current_denominator, error: min_tolerance, irrational_id: @irrational.id)
        elsif exponent < seen_significance # a match on a better magnitude, record this fit
          model.create(numerator: current_numerator, denominator: current_denominator, error: min_tolerance, irrational_id: @irrational.id)
          seen_significance = exponent
        end
      end
    end
  end

  def implant_fractions_and_function(model, function, name, start)
    max_iterations = 50
    max_inner = 10

    model.where(irrational_id: @irrational.id).delete_all # clear out potentially old data

    min_tolerance = 0.1
    seen_significance = -1
    (start..max_iterations).each do |root_test|
      current_numerator = 0
      current_denominator = 1
      root_value = function.call(root_test)
      match_value = @irrational.input/root_value
      current_test = current_numerator.to_f/current_denominator
      (1..max_inner).each do
        if current_test < match_value
          current_numerator += 1
        else
          current_denominator += 1
        end
        current_test = current_numerator.to_f/current_denominator
        test_tolerance = (current_test - match_value).abs.to_d
        if test_tolerance < min_tolerance # found a closer value
          min_tolerance = test_tolerance
          sign, significant_digits, base, exponent = test_tolerance.split
          if significant_digits == "0"  # perfect match
            return model.create(name.to_sym => root_test, numerator: current_numerator, denominator: current_denominator, error: min_tolerance, irrational_id: @irrational.id)
          elsif exponent < seen_significance # a match on a better magnitude, record this fit
            model.create(name.to_sym => root_test, numerator: current_numerator, denominator: current_denominator, error: min_tolerance, irrational_id: @irrational.id)
            seen_significance = exponent
          end
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_irrational
      @irrational = Irrational.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def irrational_params
      params.require(:irrational).permit(:input, :exact_numerator, :exact_denominator)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pretty_print_int(decimal)
    decimal.to_s.length > 8 ? "%10.3E" % decimal.to_s : decimal.to_i
  end
end

app/helpers/irrationals_helper.rb
module IrrationalsHelper
end

app/views/irrationals/_form.html.erb
<%= form_for @irrational, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @irrational.errors.any? %>
    <div class='alert alert-danger'>
      <% @irrational.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :input, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :input, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                irrationals_path, :class => 'btn' %>
  </div>
<% end %>

app/views/irrationals/edit.html.erb
<%- model_class = Irrational -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/irrationals/index.html.erb
<%- model_class = Irrational -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:input) %></th>
      <th><%= model_class.human_attribute_name(:exact_numerator) %></th>
      <th><%= model_class.human_attribute_name(:exact_denominator) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @irrationals.each do |irrational| %>
      <tr>
        <td><%= link_to irrational.id, irrational_path(irrational) %></td>
        <td><%= pretty_print_int(irrational.input) %></td>
        <td><%= pretty_print_int(irrational.exact_numerator) %></td>
        <td><%= pretty_print_int(irrational.exact_denominator) %></td>
        <td><%=l irrational.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_irrational_path(irrational), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      irrational_path(irrational),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_irrational_path,
            :class => 'btn btn-primary' %>

app/views/irrationals/new.html.erb
<%- model_class = Irrational -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/irrationals/show.html.erb
<%- model_class = Irrational -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:input) %>:</strong></dt>
  <dd><%= @irrational.input %></dd>
  <dt><strong>Exact Value:</strong></dt>
  <dd><%= @irrational.exact_numerator.to_i %>/<%= @irrational.exact_denominator.to_i %></dd>

  <% @frac_types.each do |type| %>
    <dt><strong><%= model_class.human_attribute_name(type) %>:</strong></dt>
    <% @irrational.send(type).each do |fraction| %>
      <dd>
        <%= @irrational.input.to_i if @irrational.input.to_i != 0 && type == :fractions %> 
        <% unless fraction.denominator == 1 && fraction.numerator == 1 %>
          <% if fraction.denominator == 1 %>
            <%= fraction.numerator %>
          <% else %>
            <sup><%= fraction.numerator %></sup>
            &frasl;<sub><%= fraction.denominator %></sub>
          <% end %>
        <% end %>
        <% if type == :sqrt_fractions %>
          &radic;<span style="text-decoration:overline;">&nbsp;<%= fraction.root %>&nbsp;</span>
        <% elsif type == :pi_fractions %>
          &pi;
        <% elsif type == :e_fractions %>
          e<sup><%= fraction.power unless fraction.power == 1 %></sup>
        <% end %>
        <% sign, significant_digits, base, exponent = fraction.error.split %>
        <% unless significant_digits == "0" %>
          <span style='padding-left: 20px;'>Error: <%= base %><sup><%= exponent %></sup></span>
        <% end %>
      </dd>
    <% end %>
    <% if @irrational.send(type).nil? %>
      <dd>No <%= type %> available </dd>
    <% end %>
  <% end %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              irrationals_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_irrational_path(@irrational), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              irrational_path(@irrational),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "IrrationalMind" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'IrrationalMind', irrationals_path, :class => 'brand' %>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "New Irrational", new_irrational_path  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">This should be a most notable or interesting</li>
              <li><%= link_to "New Irrational", new_irrational_path  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Kevin Casey</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>